experiment_name: EndoSAM
model:
  class_num: 2
  sam_model_customized: true
  sam_model_type: default
  sam_model_dir: /path/to/SAM/checkpoint.pth
  encoder_size: 1024
dataset:
  class_names:
  - background
  - instrument-clapster
  dataset_dir: /path/to/your/dataset
  img_format: jpg
  ann_format: png
losses:
  ce:
    weight: 0.5
  mse:
    weight: 0.5
opt_params:
  lr_default: 0.0001
max_iter: 1
val_iter: 5
train_bs: 2
val_bs: 2
test_bs: 1
num_workers: 20
num_token: 4
log_folder: /path/to/log
model_folder: /path/to/model
ckpt_folder: /path/to/checkpoint
plot_folder: /path/to/plots
test_folder: /path/to/inference
